---
- name: enable modules
  template: src=modules.j2 dest=/etc/modules

- name: Blacklisting some kernel modules
  kernel_blacklist: "name={{ item }} state=present"
  with_items:
    - i2c-bcm2708
    - i2c-dev

- name: load modules
  modprobe: "name={{ item }} state=present"
  with_items:
    - w1-gpio
    - w1-therm

- name: clone pi-temperature-logger
  git: "repo={{ 1wire_git_url }} dest={{ 1wire_script_root }}"

- name: pi-temperature-logger config
  template: "src=local_settings.yml.j2 dest={{ 1wire_script_root }}/local_settings.yml"

- name: install Python packages
  pip: "requirements={{ 1wire_script_root }}/requirements.txt"

- name: installing the init.d startup script
  template: src=init.d.j2 dest=/etc/init.d/report_temperatures owner=root group=root mode=0755

- name: starting report_temperatures
  service: name=report_temperatures state=started enabled=yes
